-- ============================================================
-- HOPPIN — Full campus location expansion (65 new rows on top of the
-- 6 already seeded by seed.sql).
--
-- SCHEMA NOTE: this targets the real, live `locations` table (see
-- schema.sql), not a `points_of_interest` table -- that table, along with
-- seed_locations.sql / update_coordinates.sql / a `zones` table, don't
-- exist anywhere in this repo. This mirrors the same adaptation decision
-- made earlier for seed_activity_data.sql.
--
-- SKIPPED as likely duplicates of already-seeded locations (not added
-- here, to avoid two rows for the same real place):
--   - "T.P. Ganesan Auditorium" -> already exists as "TP Ganesan Auditorium"
--   - "Java (Food Court)"       -> already exists as "Java Green Food Court"
--     (its 5 named sub-outlets below still cluster on that existing point)
--
-- COORDINATES: every row is a placeholder, not a survey. Generated by
-- clustering sub-locations (food outlets, hostel blocks) around their real
-- parent building's already-seeded point where one exists, and spreading
-- new building anchors across the same CAMPUS_BOUNDS box the Leaflet map
-- restricts panning to (CampusMap.jsx), so nothing lands off-map or stacks
-- on another point. They are NOT accurate -- see the companion
-- update_coordinates_full.sql for how to correct each one later. Every row
-- is tagged -- [PLACEHOLDER] for exactly this reason.
--
-- CATEGORY: locations.category has a CHECK constraint currently limited to
-- ('canteen','library','auditorium','hostel','academic'). This script
-- widens it first -- required, or every INSERT below using a new category
-- (food_outlet/lab/gate/market/bus_stand/atm/facility) fails outright.
-- Also mirrored into schema.sql so a fresh database matches from the start.
--
-- Run once, after schema.sql + seed.sql have already been run:
--     psql "$DATABASE_URL" -f sql/seed_locations_full.sql
-- Safe to re-run only if you first delete these rows -- there is no
-- upsert/dedupe logic here (plain INSERT), unlike seed_activity_data.sql.
-- ============================================================

ALTER TABLE locations DROP CONSTRAINT IF EXISTS locations_category_check;
ALTER TABLE locations ADD CONSTRAINT locations_category_check
    CHECK (category IN (
        'canteen', 'library', 'auditorium', 'hostel', 'academic',
        'food_outlet', 'lab', 'gate', 'market', 'bus_stand', 'atm', 'facility'
    ));

INSERT INTO locations (name, category, geom) VALUES
    -- Academic / core buildings
    ('University Building', 'academic', ST_SetSRID(ST_MakePoint(80.044500, 12.823700), 4326)),  -- [PLACEHOLDER]
    ('DTP Section & Banks', 'facility', ST_SetSRID(ST_MakePoint(80.037800, 12.817500), 4326)),  -- [PLACEHOLDER]
    ('Arch Gate', 'gate', ST_SetSRID(ST_MakePoint(80.036500, 12.816800), 4326)),  -- [PLACEHOLDER]
    ('Tech Park', 'academic', ST_SetSRID(ST_MakePoint(80.045700, 12.823700), 4326)),  -- [PLACEHOLDER]
    ('Tech Park 2', 'academic', ST_SetSRID(ST_MakePoint(80.046600, 12.824200), 4326)),  -- [PLACEHOLDER]
    ('Audi Grounds', 'auditorium', ST_SetSRID(ST_MakePoint(80.042800, 12.821700), 4326)),  -- [PLACEHOLDER]
    ('Fab Lab', 'lab', ST_SetSRID(ST_MakePoint(80.042100, 12.820900), 4326)),  -- [PLACEHOLDER]
    ('BioTech Block', 'academic', ST_SetSRID(ST_MakePoint(80.040500, 12.819600), 4326)),  -- [PLACEHOLDER]
    ('Architecture Block', 'academic', ST_SetSRID(ST_MakePoint(80.041100, 12.820100), 4326)),  -- [PLACEHOLDER]
    ('MBA Block', 'academic', ST_SetSRID(ST_MakePoint(80.041700, 12.820600), 4326)),  -- [PLACEHOLDER]
    ('Vendhar Square', 'facility', ST_SetSRID(ST_MakePoint(80.044800, 12.822800), 4326)),  -- [PLACEHOLDER]
    ('Chemistry Lab', 'lab', ST_SetSRID(ST_MakePoint(80.042400, 12.821300), 4326)),  -- [PLACEHOLDER]

    -- Hostels (grid around the existing "Hostels" point)
    ('SRM Hotel', 'hostel', ST_SetSRID(ST_MakePoint(80.046600, 12.825100), 4326)),  -- [PLACEHOLDER]
    ('Paari Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.047900, 12.825100), 4326)),  -- [PLACEHOLDER]
    ('Kaari Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.049200, 12.825100), 4326)),  -- [PLACEHOLDER]
    ('Oori Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.050500, 12.825100), 4326)),  -- [PLACEHOLDER]
    ('Adhiyaman Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.051800, 12.825100), 4326)),  -- [PLACEHOLDER]
    ('Nelson Mandela Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.046600, 12.826400), 4326)),  -- [PLACEHOLDER]
    ('Sannasi Hostel (Block A)', 'hostel', ST_SetSRID(ST_MakePoint(80.047900, 12.826400), 4326)),  -- [PLACEHOLDER]
    ('Sannasi Hostel (Block B & C)', 'hostel', ST_SetSRID(ST_MakePoint(80.049200, 12.826400), 4326)),  -- [PLACEHOLDER]
    ('Agasthiyar Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.050500, 12.826400), 4326)),  -- [PLACEHOLDER]
    ('Mullai Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.051800, 12.826400), 4326)),  -- [PLACEHOLDER]
    ('Began Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.046600, 12.827700), 4326)),  -- [PLACEHOLDER]
    ('Meenakshi Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.047900, 12.827700), 4326)),  -- [PLACEHOLDER]
    ('Thamarai Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.049200, 12.827700), 4326)),  -- [PLACEHOLDER]
    ('Malligai Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.050500, 12.827700), 4326)),  -- [PLACEHOLDER]
    ('Kalpana Chawla Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.051800, 12.827700), 4326)),  -- [PLACEHOLDER]
    ('M-Block Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.046600, 12.829000), 4326)),  -- [PLACEHOLDER]
    ('Senbagam Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.047900, 12.829000), 4326)),  -- [PLACEHOLDER]
    ('ESQ Block Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.049200, 12.829000), 4326)),  -- [PLACEHOLDER]
    ('NRI Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.050500, 12.829000), 4326)),  -- [PLACEHOLDER]
    ('N Block Hostel', 'hostel', ST_SetSRID(ST_MakePoint(80.051800, 12.829000), 4326)),  -- [PLACEHOLDER]

    -- Food & campus services
    ('Boy''s Mess', 'canteen', ST_SetSRID(ST_MakePoint(80.048000, 12.825400), 4326)),  -- [PLACEHOLDER]
    ('Basic Engineering Lab (BEL)', 'lab', ST_SetSRID(ST_MakePoint(80.049200, 12.818300), 4326)),  -- [PLACEHOLDER]
    ('Durga Sami Market & Laundry', 'market', ST_SetSRID(ST_MakePoint(80.050000, 12.830000), 4326)),  -- [PLACEHOLDER]
    ('Bus Stand', 'bus_stand', ST_SetSRID(ST_MakePoint(80.036300, 12.816100), 4326)),  -- [PLACEHOLDER]

    -- Secondary engineering / lab block zone
    ('Main Entrance (Lab Block)', 'gate', ST_SetSRID(ST_MakePoint(80.049000, 12.818000), 4326)),  -- [PLACEHOLDER]
    ('Canteen (Lab Block)', 'canteen', ST_SetSRID(ST_MakePoint(80.049800, 12.818300), 4326)),  -- [PLACEHOLDER]
    ('Hi-Tech', 'academic', ST_SetSRID(ST_MakePoint(80.050200, 12.817800), 4326)),  -- [PLACEHOLDER]
    ('Mechanical Block', 'academic', ST_SetSRID(ST_MakePoint(80.050600, 12.818600), 4326)),  -- [PLACEHOLDER]
    ('Mechanical C Block', 'academic', ST_SetSRID(ST_MakePoint(80.051000, 12.819000), 4326)),  -- [PLACEHOLDER]
    ('Electrical Block', 'academic', ST_SetSRID(ST_MakePoint(80.049600, 12.819200), 4326)),  -- [PLACEHOLDER]
    ('Civil Block', 'academic', ST_SetSRID(ST_MakePoint(80.050000, 12.819600), 4326)),  -- [PLACEHOLDER]
    ('CRC Block', 'academic', ST_SetSRID(ST_MakePoint(80.049200, 12.818900), 4326)),  -- [PLACEHOLDER]
    ('Automobile Hanger', 'facility', ST_SetSRID(ST_MakePoint(80.050800, 12.817400), 4326)),  -- [PLACEHOLDER]
    ('Aerospace Hanger', 'facility', ST_SetSRID(ST_MakePoint(80.051200, 12.817800), 4326)),  -- [PLACEHOLDER]
    ('ATM', 'atm', ST_SetSRID(ST_MakePoint(80.049400, 12.818400), 4326)),  -- [PLACEHOLDER]
    ('Thermal Lab', 'lab', ST_SetSRID(ST_MakePoint(80.050400, 12.818200), 4326)),  -- [PLACEHOLDER]
    ('EV Block', 'facility', ST_SetSRID(ST_MakePoint(80.051400, 12.818600), 4326)),  -- [PLACEHOLDER]

    -- Food outlets -- clustered around their real parent building's
    -- already-seeded point (UB Ground Canteen / Java Green Food Court /
    -- Vendhar Square above)
    ('Goldie''s Grill and Shawarma (UB Ground Floor)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.043980, 12.823180), 4326)),  -- [PLACEHOLDER]
    ('Seema''s Cafe (UB First Floor)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044200, 12.823200), 4326)),  -- [PLACEHOLDER]
    ('Mr. Burger (UB First Floor)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044240, 12.823040), 4326)),  -- [PLACEHOLDER]
    ('Fritesphere (UB First Floor)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044020, 12.822980), 4326)),  -- [PLACEHOLDER]
    ('Chaat Addaa (UB First Floor)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044160, 12.823240), 4326)),  -- [PLACEHOLDER]
    ('SRM Evergreen (UB First Floor)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.043960, 12.823060), 4326)),  -- [PLACEHOLDER]
    ('Queen''s Court (Java Food Court)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044500, 12.823670), 4326)),  -- [PLACEHOLDER]
    ('Subway (Java Food Court)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044690, 12.823690), 4326)),  -- [PLACEHOLDER]
    ('Loaded Fries (Java Food Court)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044720, 12.823550), 4326)),  -- [PLACEHOLDER]
    ('Shakes and Desserts (Java Food Court)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044530, 12.823500), 4326)),  -- [PLACEHOLDER]
    ('Classic Biryani (Java Food Court)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044650, 12.823720), 4326)),  -- [PLACEHOLDER]
    ('Domino''s Pizza (Vendhar Square)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044700, 12.822860), 4326)),  -- [PLACEHOLDER]
    ('Zinger (Vendhar Square)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044900, 12.822880), 4326)),  -- [PLACEHOLDER]
    ('Triangle Social Cafe (Vendhar Square)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.044820, 12.822680), 4326)),  -- [PLACEHOLDER]

    -- Not part of any building listed elsewhere in the request ("Hotel
    -- Management Block" / "SRM Global Hospital" aren't in the location
    -- list themselves) -- own small placeholder anchors near the campus
    -- edge, not implying those buildings are mapped yet.
    ('Genz Beta Cafe (Near Hotel Management Block)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.042000, 12.820200), 4326)),  -- [PLACEHOLDER]
    ('Slice Of Life (Near SRM Global Hospital)', 'food_outlet', ST_SetSRID(ST_MakePoint(80.052500, 12.831500), 4326));  -- [PLACEHOLDER]
